### ISSUE TITLE
24h-lemans.com - RSE - Ajout pdf

### ISSUE THREAD

**Issue by jrroger-aco** [Happyend/GenericForm#32]
Sur la page https://www.24h-lemans.com/fr/rse/pour-la-planete
Ajouter un CTA permettant de télécharger le document suivant

FR => https://assets.lemans.org/explorer/pdf/aco/2022/rse/bilan-carbone-fr.pdf
UK => https://assets.lemans.org/explorer/pdf/aco/2022/rse/bilan-carbone-uk.pdf

**Comment by driplo** [comment]
Je peux ajouter une option au composant du haut de page pour recevoir un CTA:



![Image](https://user-images.githubusercontent.com/6059244/204773273-d5cd1c4b-c183-453a-ba2f-07eed0b73b2a.png)

**Comment by jrroger-aco** [comment]
@driplo ok

**Comment by driplo** [comment]
Dispo en PP:

https://lemans-pp.happyend.com/fr/rse/pour-la-planete
https://lemans-pp.happyend.com/en/csr/for-the-planet

**Comment by driplo** [comment]
Dispo en prod:
https://www.24h-lemans.com/fr/rse/pour-la-planete
